// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace EfLibrary.Models;

[Table("products-quantity")]
[Index("ProductId", Name = "product_id_fk")]
public partial class ProductsQuantity
{
    [Key]
    [Column("quantity_id", TypeName = "int(11)")]
    public int QuantityId { get; set; }

    [Column("product_id", TypeName = "int(11)")]
    public int? ProductId { get; set; }

    [Column("product_quantity", TypeName = "int(11)")]
    public int? ProductQuantity { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductsQuantities")]
    public virtual Product? Product { get; set; }
}