// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace EfLibrary.Models;

[Table("transaction-item")]
[Index("ProductId", Name = "product_id")]
[Index("TransactionId", Name = "transaction_id")]
public partial class TransactionItem
{
    [Key]
    [Column("id", TypeName = "int(11)")]
    public int Id { get; set; }

    [Column("transaction_id", TypeName = "int(11)")]
    public int? TransactionId { get; set; }

    [Column("product_id", TypeName = "int(11)")]
    public int? ProductId { get; set; }

    [Column("quantity", TypeName = "int(11)")]
    public int? Quantity { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("TransactionItems")]
    public virtual Product? Product { get; set; }

    [ForeignKey("TransactionId")]
    [InverseProperty("TransactionItems")]
    public virtual Transaction? Transaction { get; set; }
}